export const Persons = {
  KEIRA_KNIGHTLEY : { EN_US : "Keira Knightley", RU : "Кира Найтли" },
  JAKE_GYLLENHAAL : { EN_US : "Jake Gyllenhaal", RU : "Джейк Джилленхол" },
  GUY_RITCHIE : { EN_US : "Guy Ritchie", RU : "Гай Ричи" },
  CHRISTOPHER_NOLAN : { EN_US : "Christopher Nolan", RU : "Кристофер Нолан" },
  MATTHEW_MCCONAUGHEY : { EN_US : "Matthew McConaughey", RU : "Мэттью МакКонахи" },
  JAMES_CAMERON : { EN_US : "James Cameron", RU : "Джеймс Кэмерон" },
  ARNOLD_SCHWARZENEGGER : { EN_US : "Arnold Schwarzenegger", RU : "Арнольд Шварцнеггер" },
  CHRISTIAN_BALE : { EN_US : "Christian Bale", RU : "Кристиан Бэйл" },
  SAM_WORTHINGTON : { EN_US : "Sam Worthington", RU : "Сэм Уортингтон" },
  EMILIA_CLARKE : { EN_US : "Emilia Clarke", RU : "Эмилия Кларк" },
  ANNE_HATHAWAY : { EN_US : "Anne Hathaway", RU : "Энн Хэтэуэй" },
  MATT_DAMON : { EN_US : "Matt Damon", RU : "Мэтт Дэймон" },
  CASEY_AFFLECK : { EN_US : "Casey Affleck", RU : "Кейси Аффлек" },
  LEONARDO_DICAPRIO : { EN_US : "Leonardo DiCaprio", RU : "Леонардо Дикаприо" },
  JOSEPH_GORDON_LEVITT : { EN_US : "Joseph Gordon-Levitt", RU : "Джозеф Гордон-Левитт" },
  CILLIAN_MURPHY : { EN_US : "Cillian Murphy", RU : "Киллиан Мерфи" },
  TOM_HARDY : { EN_US : "Tom Hardy", RU : "Том Харди" },
  MARION_COTILLARD : { EN_US : "Marion Cotillard", RU : "Марион Котийяр" },
  HEATH_LEDGER : { EN_US : "Heath Ledger", RU : "Хит Леджер" },
  GARY_OLDMAN : { EN_US : "Gary Oldman", RU : "Гэри Олдман" },
  MORGAN_FREEMAN : { EN_US : "Morgan Freeman", RU : "Морган Фриман" },
  HUGH_JACKMAN : { EN_US : "Hugh Jackman", RU : "Хью Джекман" },
  SCARLETT_JOHANSSON : { EN_US : "Scarlett Johansson", RU : "Скарлетт Йоханссон" },
  PIPER_PERABO : { EN_US : "Piper Perabo", RU : "Пайпер Перабо" },
  JACK_NICHOLSON : { EN_US : "Jack Nicholson", RU : "Джек Николсон" },
  MARTIN_SCORSESE : { EN_US : "Martin Scorsese", RU : "Мартин Скорсезе" },
  ORLANDO_BLOOM : { EN_US : "Orlando Bloom", RU : "Орландо Блум" },
  CATE_BLANCHETT : { EN_US : "Cate Blanchett", RU : "Кейт Бланшетт" },
  SEAN_BEAN : { EN_US : "Sean Bean", RU : "Шон Бин" },
  ADRIEN_BRODY : { EN_US : "Adrien Brody", RU : "Эдриан Броуди" },
  RIDLEY_SCOTT : { EN_US : "Ridley Scott", RU : "Ридли Скотт" },
  RUSSELL_CROWE : { EN_US : "Russell Crowe", RU : "Рассел Кроу" },
  JOAQUIN_PHOENIX : { EN_US : "Joaquin Phoenix", RU : "Хоакин Феникс" },
  TOM_HANKS : { EN_US : "Tom Hanks", RU : "Том Хэнкс" },
  FRANK_DARABONT : { EN_US : "Frank Darabont", RU : "Фрэнк Дарабонт" },
  DAVID_FINCHER : { EN_US : "David Fincher", RU : "Дэвид Финчер" },
  EDWARD_NORTON : { EN_US : "Edward Norton", RU : "Эдвард Нортон" },
  BRAD_PITT : { EN_US : "Brad Pitt", RU : "Брэд Питт" },
  JARED_LETO : { EN_US : "Jared Leto", RU : "Джаред Лето" },
  STEVEN_SPIELBERG : { EN_US : "Steven Spielberg", RU : "Стивен Спилберг" },
  VIN_DIESEL : { EN_US : "Vin Diesel", RU : "Вин дизель" },
  KEVIN_SPACEY : { EN_US : "Kevin Spacey", RU : "Кевин Спейси" },
  QUENTIN_TARANTINO : { EN_US : "Quentin Tarantino", RU : "Квентин Тарантино" },
  JOHN_TRAVOLTA : { EN_US : "John Travolta", RU : "Джон Траволта" },
  SAMUEL_L_JACKSON : { EN_US : "Samuel L. Jackson", RU : "Сэмюэл Л. Джексон" },
  UMA_THURMAN : { EN_US : "Uma Thurman", RU : "Ума Турман" },
  BRUCE_WILLIS : { EN_US : "Bruce Willis", RU : "Брюс Уиллис" },
  LIAM_NEESON : { EN_US : "Liam Neeson", RU : "Лиам Нисон" },
  ANTHONY_HOPKINS : { EN_US : "Anthony Hopkins", RU : "Энтони Хопкинс" },
  ROBERT_DE_NIRO : { EN_US : "Robert De Niro", RU : "Роберт Де Ниро" },
  AL_CAPINO : { EN_US : "Al Pacino", RU : "Аль Пачино" },
  CLINT_EASTWOOD : { EN_US : "Clint Eastwood", RU : "Клинт Иствуд" },
  MARK_WAHLBERG : { EN_US : "Mark Wahlberg", RU : "Марк Уолберг" },
  MONICA_BELLUCCI : { EN_US : "Monica Bellucci", RU : "Моника Беллуччи" },
  KEANU_REEVES : { EN_US : "Keanu Reeves", RU : "Киану Ривз" },
  ADAM_SANDLER : { EN_US : "Adam Sandler", RU : "Адам Сэндлер" },
  JENNIFER_ANISTON : { EN_US : "Jennifer Aniston", RU : "Дженнифер Энистон" },
  CHRIS_HEMSWORTH : { EN_US : "Chris Hemsworth", RU : "Крис Хемсворт" },
  OLGA_KURYLENKO : { EN_US : "Olga Kurylenko", RU : "Ольга Куриленко" },
  IDRIS_ELBA : { EN_US : "Idris Elba", RU : "Идрис Эльба" },
  LOUIS_LETERRIER : { EN_US : "Louis Leterrier", RU : "Луи Летерье" },
  JASON_MOMOA : { EN_US : "Jason Momoa", RU : "Джейсон Момоа" },
  JASON_STATHEM : { EN_US : "Jason Statham", RU : "Джейсон Стэтхэм" },
  CHARLIZE_THERON : { EN_US : "Charlize Theron", RU : "Шарлиз Терон" },
  CHRIS_PRATT : { EN_US : "Chris Pratt", RU : "Крис Пратт" },
  GAL_GADOT : { EN_US : "Gal Gadot", RU : "Галь Гадот" },
  KATE_WINSLET : { EN_US : "Kate Winslet", RU : "Кейт Уинслет" },
  SCOTT_ADKINS : { EN_US : "Scott Adkins", RU : "Скотт Адкинс" },
  JENNIFER_LAWRENCE : { EN_US : "Jennifer Lawrence", RU : "Дженифер Лоуренс" },
  EVANGELINE_LILLY : { EN_US : "Evangeline Lilly", RU : "Эванджелин Лилли" },
  MICHELLE_PFEIFFER : { EN_US : "Michelle Pfeiffer", RU : "Мишель Пфайффер" },
  MICHAEL_DOUGLAS : { EN_US : "Michael Douglas", RU : "Майкл Дуглас" },
  MARGOT_ROBBIE  : { EN_US : "Margot Robbie", RU : "Марго Робби" },
  RYAN_GOSLING : { EN_US : "Ryan Gosling", RU : "Райан Гослинг" },
  WILL_FERRELL : { EN_US : "Will Ferrell", RU : "Уилл Феррелл" },
  HARRISON_FORD : { EN_US : "Harrison Ford", RU : "Харрисон Форд" },
  ANTONIO_BANDERAS : { EN_US : "Antonio Banderas", RU : "Антонио Бандерас" },
  BEN_AFFLECK : { EN_US : "Ben Affleck", RU : "Бен Аффлек" },
  GERARD_BUTLER : { EN_US : "Gerard Butler", RU : "Джерард Батлер" },
  SALMA_HAYEK : { EN_US : "Salma Hayek", RU : "Сальма Хайек" },
  CHANNING_TATUM : { EN_US : "Channing Tatum", RU : "Чаннинг Татум" },
  TOM_CRUISE : { EN_US : "Tom Cruise", RU : "Том Круз" },
  JENNIFER_CONNELLY : { EN_US : "Jennifer Connelly", RU : "Дженнифер Коннелли" },
  ANA_DE_ARMAS : { EN_US : "Ana de Armas", RU : "Ана де Армас" },
  DANIEL_CRAIG : { EN_US : "Daniel Craig", RU : "Дэниел Крейг" },
  CHRIS_EVANS : { EN_US : "Chris Evans", RU : "Крис Эванс" },
  SYLVESTER_STALLONE : { EN_US : "Sylvester Stallone", RU : "Сильвестр Сталлоне" },
  DENZEL_WASHINGTON : { EN_US : "Denzel Washington", RU : "Дензел Вашингтон" },
  EMILY_BLUNT : { EN_US : "Emily Blunt", RU : "Эмили Блант" },
  ROBERT_DOWNEY_JR : { EN_US : "Robert Downey Jr.", RU : "Роберт Дауни-младший." },
  JOSH_HARNETT : { EN_US : "Josh Hartnett", RU : "Джош Хартнетт" },
  GUY_PEARCE : { EN_US : "Guy Pearce", RU : "Гай Пирс" },
  MEL_GIBSON : { EN_US : "Mel Gibson", RU : "Мел Гибсон" },
  TERESA_PALMER : { EN_US : "Teresa Palmer", RU : "Тереза Палмер" },
  JAMIE_FOXX : { EN_US : "Jamie Foxx", RU : "Джейми Фокс" },
  ROSAMUND_PIKE : { EN_US : "Rosamund Pike", RU : "Розамунд Пайк" },
  JEAN_RENO : { EN_US : "Jean Reno", RU : "Жан Рено" },
  NATALIE_PORTMAN : { EN_US : "Natalie Portman", RU : "Натали Портман" },
  LUC_BESSON : { EN_US : "Luc Besson", RU : "Люк Бессон" },
  ALFRED_HITCHCOCK : { EN_US : "Alfred Hitchcock", RU : "Альфред Хичкок" },
  ELIZABETH_OLSEN : { EN_US : "Elizabeth Olsen", RU : "Элизабет Олсен" },
  BENEDICT_CUMBERBATCH : { EN_US : "Benedict Cumberbatch", RU : "Бенедикт Камбербэтч" },
  ZACK_SNYDER : { EN_US : "Zack Snyder", RU : "Зак Снайдер" },
  EDDIE_MURPHY : { EN_US : "Eddie Murphy", RU : "Эдди Мерфи" },
  TOMMY_LEE_JONES : { EN_US : "Tommy Lee Jones", RU : "Томми Ли Джонс" },
  BEN_FOSTER : { EN_US : "Ben Foster", RU : "Бен Фостер" },
  AMBER_HEARD : { EN_US : "Amber Heard", RU : "Эмбер Херд" },
  NICOLE_KIDMAN : { EN_US : "Nicole Kidman", RU : "Николь Кидман" },
  ROBIN_WILLIAMS : { EN_US : "Robin Williams", RU : "Робин Уильямс" },
  SEAN_CONNERY : { EN_US : "Sean Connery", RU : "Шон Коннери" },
  MICHAEL_FASSBENDER : { EN_US : "Michael Fassbender", RU : "Майкл Фассбендер" },
  KEVIN_HART : { EN_US : "Kevin Hart", RU : "Кевин Харт" }
} as const;

export class Person {
  readonly code: keyof typeof Persons;
  
  public constructor(code: keyof typeof Persons) {
    if (!(code in Persons)) {
      throw new InvalidPersonError();
    }
    this.code = code;
  }
}

class InvalidPersonError extends Error {}
